# ABOUTME: Reusable Python test workflow - callable from any repository
name: Python Tests (Reusable)

on:
  workflow_call:
    inputs:
      python-version:
        description: 'Python version to use'
        required: false
        type: string
        default: '3.11'
      pre-install-command:
        description: 'Command to run before dependency installation (e.g., apt-get install system packages)'
        required: false
        type: string
        default: ''
      install-command:
        description: 'Command to install dependencies (use uv sync per CLAUDE.md)'
        required: false
        type: string
        default: 'uv sync'
      test-command:
        description: 'Command to run tests'
        required: false
        type: string
        default: 'uv run pytest --cov --cov-report=term-missing'
      working-directory:
        description: 'Working directory for tests'
        required: false
        type: string
        default: '.'

jobs:
  test:
    name: Run Test Suite
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ inputs.python-version }}

      - name: Install UV
        run: curl -LsSf https://astral.sh/uv/install.sh | sh

      - name: Run pre-install commands
        if: inputs.pre-install-command != ''
        working-directory: ${{ inputs.working-directory }}
        run: ${{ inputs.pre-install-command }}

      - name: Install dependencies
        working-directory: ${{ inputs.working-directory }}
        run: ${{ inputs.install-command }}

      - name: Run tests
        working-directory: ${{ inputs.working-directory }}
        run: ${{ inputs.test-command }}

      - name: Verify tests passed
        run: |
          echo "✅ All tests passed successfully"
          echo ""
          echo "Per CLAUDE.md Section 3: TDD is MANDATORY"
          echo "All features must have tests before merging"
